import {
  LOGIN_USER, REFRESH_TOKEN,
} from './auth/auth.gql'

import {
  GET_USERS, GET_USER, CREATE_USER, UPDATE_USER, DELETE_USER,
} from './users/users.gql'

import {
  GET_POSTS, GET_POST, CREATE_POST, UPDATE_POST, DELETE_POST,
} from './posts/posts.gql'

import {
  GET_MAPS, CREATE_MAP,
} from './maps/maps.gql'

import {
  GET_MINDMAPS, GET_MINDMAP, CREATE_MINDMAP,
} from './mindmaps/mindmaps.gql'

import {
  SUBSCRIBE_TO_MESSAGES, GET_MESSAGES, POST_MESSAGE,
} from './chat/chat.gql'

import {
  SUBSCRIBE_TO_BOARD, POST_UPDATED_ELEMENT, GET_BOARDS, GET_BOARD, CREATE_BOARD, UPDATE_BOARD, DELETE_BOARD,
} from './whiteboard/whiteboard.gql'

export {
  LOGIN_USER, REFRESH_TOKEN,
  GET_USERS, GET_USER, CREATE_USER, UPDATE_USER, DELETE_USER,
  GET_POSTS, GET_POST, CREATE_POST, UPDATE_POST, DELETE_POST,
  GET_MAPS, CREATE_MAP,
  GET_MINDMAPS, GET_MINDMAP, CREATE_MINDMAP,
  GET_MESSAGES, POST_MESSAGE, SUBSCRIBE_TO_MESSAGES,
  SUBSCRIBE_TO_BOARD, POST_UPDATED_ELEMENT, GET_BOARDS, GET_BOARD, CREATE_BOARD, UPDATE_BOARD, DELETE_BOARD,
}