import {
  SIGNUP_USER, LOGIN_USER, REFRESH_TOKEN,
} from './auth/auth.gql'

import {
  GET_USERS, GET_USER, CREATE_USER, UPDATE_USER, DELETE_USER,
} from './users/users.gql'

import {
  GET_POSTS, GET_POST, CREATE_POST, UPDATE_POST, DELETE_POST,
} from './posts/posts.gql'

import {
  GET_MAPS, CREATE_MAP, DELETE_MAP,
} from './maps/maps.gql'

import {
  GET_MINDMAPS, GET_MINDMAP, CREATE_MINDMAP, DELETE_MINDMAP,
} from './mindmaps/mindmaps.gql'

import {
  SUBSCRIBE_TO_MESSAGES, GET_MESSAGES, POST_MESSAGE,
} from './chat/chat.gql'

import {
  SUBSCRIBE_TO_BOARD, POST_UPDATED_ELEMENT, GET_BOARDS, GET_BOARD, CREATE_BOARD, UPDATE_BOARD, DELETE_BOARD,
} from './whiteboard/whiteboard.gql'

import {
  GET_FILES, GET_FILE, UPLOAD_SINGLE_FILE, UPLOAD_MULTIPLE_FILES, DELETE_FILE,
} from './files/file.gql'

import {
  GET_TAGS,
} from './tags/tag.gql'

export {
  // Auth
  SIGNUP_USER, LOGIN_USER, REFRESH_TOKEN,
  // User
  GET_USERS, GET_USER, CREATE_USER, UPDATE_USER, DELETE_USER,
  // Blog
  GET_POSTS, GET_POST, CREATE_POST, UPDATE_POST, DELETE_POST,
  // Maps
  GET_MAPS, CREATE_MAP, DELETE_MAP,
  // Mindmaps
  GET_MINDMAPS, GET_MINDMAP, CREATE_MINDMAP, DELETE_MINDMAP,
  // Chat
  GET_MESSAGES, POST_MESSAGE, SUBSCRIBE_TO_MESSAGES,
  // Whiteboard
  SUBSCRIBE_TO_BOARD, POST_UPDATED_ELEMENT, GET_BOARDS, GET_BOARD, CREATE_BOARD, UPDATE_BOARD, DELETE_BOARD,
  // Fileuploaad
  GET_FILES, GET_FILE, UPLOAD_SINGLE_FILE, UPLOAD_MULTIPLE_FILES, DELETE_FILE,
  // Tags
  GET_TAGS,
}